# Generated by Django 5.0.6 on 2026-06-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='solutions/')),
                ('status', models.CharField(choices=[('deployed', 'Deployed'), ('in_development', 'In Development'), ('ready_to_launch', 'Ready to Launch')], default='deployed', max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('technologies', models.JSONField(blank=True, default=list, help_text='List of tech/stack strings')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
