# Generated by Django 5.0.6 on 2026-06-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_industry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
