# Generated by Django 5.0.6 on 2026-06-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('interest', models.CharField(choices=[('virtual_assistant', 'AI-Powered Virtual Assistant'), ('schedule_demo', 'Schedule a Demo'), ('events', 'Promotional Events'), ('sales', 'Chat with Sales'), ('general', 'General Inquiry')], default='general', max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
