# Generated by Django 5.0.6 on 2026-06-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
